apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-postgres
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
    component: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: postgres
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "myapp.name" . }}
    component: postgres
